### PR TITLE
Proposed version 5.0

### PR DESCRIPTION
**Pull request by LlmDl**
Changes PlayerLoginEvent for AsyncPlayerPreLoginEvent.
Adds logging output when a name change is detected.
Denies players access on their first attempt to join in order to give
more time for Towny to update its database.
Updates Towny version in pom.xml.

### CODE REVIEW

**Comment by ghost** [comment]
I guess my main question is what is the root problem and how do these changes _specifically_ solve them?

**Comment by LlmDl** [comment]
Well this would be having us acting earlier than before (AsyncPlayerPreLoginEvent instead of PlayerLoginEvent,) and it will make sure the login isn't allowed, so the DBHandler has more time to rename the player.

**Comment by ghost** [comment]
> Well this would be having us acting earlier than before (AsyncPlayerPreLoginEvent instead of PlayerLoginEvent,) and it will make sure the login isn't allowed, so the DBHandler has more time to rename the player.

Is there a sync PrePlayerLoginEvent?

**Comment by LlmDl** [comment]
> > Well this would be having us acting earlier than before (AsyncPlayerPreLoginEvent instead of PlayerLoginEvent,) and it will make sure the login isn't allowed, so the DBHandler has more time to rename the player.
> 
> Is there a sync PrePlayerLoginEvent?

It exists but was deprecated for the Async one.

**Comment by ghost** [comment]
There's not much I can offer then, you'll just have to test it.

**Pull request merged**
